name: ansi_pixels
description: A Polymer.dart application to edit ANSI art
environment:
  sdk: '>=1.6.0'
dependencies:
  ansi_color_palette: '>=1.2.0 <1.3.0'
  archive: '>=1.0.0 <1.1.0'
  crypto: '>=0.9.0 <0.10.0'
  fold_button: '>=1.1.0 <1.2.0'
  pixel_canvas: '>=1.1.0 <1.2.0'
  polymer: '>=0.13.0 <0.14.0'
dev_dependencies:
  ghpages_generator: '>=0.2.0 <0.3.0'
  path: '>=1.2.0 <1.3.0'
  yaml: '>=1.1.0 <1.2.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
