name: ansi_pixels
description: A Polymer.dart application to edit ANSI art
environment:
  sdk: '>=1.11.0'
dependencies:
  polymer: '>=0.16.0 <0.17.0'
  core_elements: '>=0.7.1 <0.8.0'
  archive: '>=1.0.0 <1.1.0'
  crypto: '>=0.9.0 <0.10.0'
  ansi_color_palette: '>=1.3.0 <1.4.0'
  fold_button: '>=1.2.0 <1.3.0'
  pixel_canvas: '>=1.2.0 <1.3.0'
dev_dependencies:
  ghpages_generator: '>=0.3.0 <0.4.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
